---
id: 331124
name: box->Snowflake
description: ''
user:
  id: 6335
  email: sayo.kimura+demo@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: box
    box_connection:
      id: 19
      name: csdemo-Box
    folder_id: '267303136031'
    file_prefix: '250421'
    decompression_type:
    stop_when_file_not_found: false
    custom_variables: []
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 0
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: UTF-8
      columns: []
      quote: "\""
      escape: "\\"
    decoders: []
  out:
    type: snowflake
    snowflake_connection:
      id: 47
      name: csdemo-Snowflake
    warehouse: COMPUTE_WH
    database: TEST_BY_KIMURA
    schema: PUBLIC
    table: TSV_25421
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
notifications: []
