---
id: 335167
name: box -> Snowflake
description: ''
user:
  id: 6335
  email: sayo.kimura+demo@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: box
    box_connection:
      id: 259
      name: sample-Box
    folder_id: '111111 '
    file_prefix: sample_customer_data.csv
    decompression_type:
    stop_when_file_not_found: false
    custom_variables: []
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: CRLF
      charset: UTF-8
      columns:
      - name: 氏名
        type: string
      - name: 氏名（ひらがな）
        type: string
      - name: 年齢
        type: long
      - name: 生年月日
        type: string
      - name: 性別
        type: string
      - name: メールアドレス
        type: string
      - name: 携帯電話番号
        type: string
      - name: 郵便番号
        type: string
      - name: 住所
        type: string
      quote: "\""
      escape: "\""
    decoders: []
  out:
    type: snowflake
    snowflake_connection:
      id: 47
      name: csdemo-Snowflake
    warehouse: COMPUTE_WH
    database: DEMO_DB
    schema: PUBLIC
    table: CUSTOMER_DATA
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: NAME
      src: 氏名
      default: ''
      type: string
    - name: AGE
      src: 性別
      default: ''
      type: string
    - name: EMAIL
      src: メールアドレス
      default: ''
      type: string
    - name: PHONE
      src: 携帯電話番号
      default: ''
      type: string
    - name: ADDRESS
      src: 住所
      default: ''
      type: string
    row_filters:
      condition: and
      conditions:
      - column: 性別
        operator: "=="
        argument: 女
    masking:
      columns:
      - type: email
        length: 8
        name: EMAIL
    string_replacement_columns:
      target_columns:
        PHONE:
        - type: regexp_replace
          pattern: "-"
          to: ''
    filter_string_transforms:
    - column_name: ADDRESS
      type: normalize_nfkc
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
notifications: []
