---
id: 344505
name: date検証
description: ''
user:
  id: 6335
  email: sayo.kimura+demo@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: google_spreadsheets
    google_spreadsheets_connection:
      id: 1123
      name: kimura-GoogleSpreadsheets
    spreadsheets_url: https://docs.google.com/spreadsheets/d/1JV07h0Bn4WB-BZHvIg0N9dYVYmo010EHdLoGP4AvvtI/edit?gid=0#gid=0
    worksheet_title: 名簿
    start_row: 2
    start_column: A
    default_timezone: Asia/Tokyo
    null_string: ''
    columns:
    - name: id
      type: string
    - name: name
      type: string
    - name: age
      type: string
    - name: 日付
      type: string
    - name: 数値
      type: string
    - name: Clicks
      type: string
    custom_variables:
    - type: timestamp
      name: "$date$"
      quantity: 0
      unit: hour
      direction: ago
      time_zone: Asia/Tokyo
      format: "%Y-%m-%d %H:%M:%S.%3N %z"
  out:
    type: snowflake
    snowflake_connection:
      id: 47
      name: csdemo-Snowflake
    warehouse: COMPUTE_WH
    database: TEST_BY_KIMURA
    schema: PUBLIC
    table: DATE_TEST
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
      date:
        type: TIMESTAMP
        timezone: JST
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: string
    - name: name
      src: name
      default: ''
      type: string
    - name: age
      src: age
      default: ''
      type: string
    - name: 日付
      src: 日付
      default: ''
      type: string
    - name: 数値
      src: 数値
      default: ''
      type: string
    - name: Clicks
      src: Clicks
      default: ''
      type: string
    - name: date
      src: ''
      default: "$date$"
      type: timestamp
      format: ''
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
notifications: []
