---
id: 330926
name: Google Drive -> Snowflake
description: ''
user:
  id: 6335
  email: sayo.kimura+demo@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: google_drive
    google_drive_connection:
      id: 325
      name: csdemo-GoogleDrive-kimura
    folder_id: 1uwrFP5N2n9_a9yGaWmF8HN6MNjCN6_tv
    file_match_pattern: sample_customer_data.csv
    decompression_type:
    skip_header_line: false
    custom_variables: []
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: CRLF
      charset: UTF-8
      columns:
      - name: 氏名
        type: string
      - name: 氏名（ひらがな）
        type: string
      - name: 年齢
        type: long
      - name: 生年月日
        type: string
      - name: 性別
        type: string
      - name: メールアドレス
        type: string
      - name: 携帯電話番号
        type: string
      - name: 郵便番号
        type: string
      - name: 住所
        type: string
      quote: "\""
      escape: "\""
    decoders: []
  out:
    type: snowflake
    snowflake_connection:
      id: 1568
      name: Snowflake - クックブック
    warehouse: COMPUTE_WH
    database: COOKBOOK
    schema: PUBLIC
    table: SAMPLE_CUSTOMER_DATA
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: NAME
      src: 氏名
      default: ''
      type: string
    - name: AGE
      src: 年齢
      default: ''
      type: long
    - name: BIRTHDAY
      src: 生年月日
      default: ''
      type: string
    - name: GENDER
      src: 性別
      default: ''
      type: string
    - name: EMAIL
      src: メールアドレス
      default: ''
      type: string
    - name: NUMBER
      src: 携帯電話番号
      default: ''
      type: string
    - name: ZIP_CODE
      src: 郵便番号
      default: ''
      type: string
    - name: ADDRESS
      src: 住所
      default: ''
      type: string
    row_filters:
      condition: and
      conditions:
      - column: 年齢
        operator: ">"
        argument: '20'
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
notifications: []
