---
id: 329917
name: クックブック用
description: ''
user:
  id: 6335
  email: sayo.kimura+demo@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: s3
    s3_connection:
      id: 668
      name: csdemo-AmazonS3
    region: ap-northeast-1
    bucket: trocco-test-kimura
    path_prefix: cook_book/snowflake_timestamp_1
    path_match_pattern: ''
    decompression_type: guess
    skip_header_line: false
    stop_when_file_not_found: false
    custom_variables: []
    incremental_loading_enabled: false
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: ISO-8859-2
      columns:
      - name: id
        type: string
      - name: date
        type: string
        format: "%Y-%m-%d %H:%M:%S %z"
      quote: "\""
      escape: "\""
    decoders: []
  out:
    type: snowflake
    snowflake_connection:
      id: 1568
      name: Snowflake - クックブック
    warehouse: COMPUTE_WH
    database: COOKBOOK
    schema: PUBLIC
    table: STRING_TEST
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
      date:
        type: TIMESTAMP
        value_type: string
        timestamp_format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: string
    - name: date
      src: date
      default: ''
      type: string
    string_replacement_columns:
      target_columns:
        date:
        - type: regexp_replace
          pattern: "(\\d{4})-(\\d{2})-(\\d{2}) (\\d{2}):(\\d{2}):(\\d{2}).(\\d{3})"
          to: "$1-$2-$3 $4:$5:$6"
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
notifications: []
