---
id: 357896
name: タイムゾーンの検証
description: ''
user:
  id: 6335
  email: sayo.kimura+demo@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: box
    box_connection:
      id: 19
      name: csdemo-Box
    folder_id: '267303136031'
    file_prefix: 0606.csv
    decompression_type:
    stop_when_file_not_found: false
    custom_variables: []
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: UTF-8
      columns:
      - name: c0
        type: timestamp
        format: "%Y-%m-%d %H:%M:%S %Z"
      - name: c1
        type: timestamp
        format: "%Y-%m-%d %H:%M:%S %Z"
      - name: c2
        type: timestamp
        format: "%Y-%m-%d %H:%M:%S %Z"
      quote: "\""
      escape: "\""
    decoders: []
  out:
    type: snowflake
    snowflake_connection:
      id: 47
      name: csdemo-Snowflake
    warehouse: COMPUTE_WH
    database: TEST_BY_KIMURA
    schema: PUBLIC
    table: '0701'
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
      c0:
        type: TIMESTAMP
        timezone: UTC
      c1:
        type: TIMESTAMP
        timezone: Asia/Tokyo
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: c0
      src: c0
      default: ''
      type: timestamp
      format: "%Y-%m-%d %H:%M:%S %Z"
    - name: c1
      src: c1
      default: ''
      type: timestamp
      format: "%Y-%m-%d %H:%M:%S %Z"
    - name: c2
      src: c2
      default: ''
      type: timestamp
      format: "%Y-%m-%d %H:%M:%S %Z"
    transfered_time_column:
      column_name: time
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
notifications: []
