---
id: 285976
name: 日付、カスタム変数検証
description: ''
user:
  id: 6335
  email: sayo.kimura+demo@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: google_drive
    google_drive_connection:
      id: 325
      name: csdemo-GoogleDrive-kimura
    folder_id: 1RB1VkempURydDvSUeng3S969DCgihKro
    file_match_pattern: sample$date$
    decompression_type:
    skip_header_line: false
    custom_variables:
    - type: timestamp
      name: "$date$"
      quantity: 1
      unit: date
      direction: ago
      time_zone: Asia/Tokyo
      format: "%Y%m%d"
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: UTF-8
      columns:
      - name: id
        type: long
      - name: name
        type: string
      - name: text
        type: string
      quote: "\""
      escape: "\""
    decoders: []
  out:
    type: snowflake
    snowflake_connection:
      id: 47
      name: csdemo-Snowflake
    warehouse: COMPUTE_WH
    database: TEST_BY_KIMURA
    schema: PUBLIC
    table: 1202_test
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: long
    - name: name
      src: name
      default: ''
      type: string
    - name: text
      src: text
      default: ''
      type: string
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
notifications: []
